apiVersion: apps/v1
kind: Deployment
metadata:
  name: utn-node-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utn-node
  template:
    metadata:
      labels:
        app: utn-node
    spec:
      containers:
      - name: utn-node
        image: fernandeznicodev/utn-nodejs-image
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: utn-node-service
spec:
  type: NodePort
  selector:
    app: utn-node
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000